name: GuardianGolems
version: '0.1.0'
main: net.hyper_pigeon.guardian_golems.GuardianGolems
api-version: '1.21.11'
authors: [ HyperPigeon ]
description: A plugin that adds loyal, guard golems to Minecraft. 
